# 配置模版，正式去掉后缀template

WSAddr         = "10.128.2.252:4546"     # websocket地址
HttpAddr       = "10.128.2.252:4545"     # 服务器地址
LoadDir        = "./app"              # 加载目录
ExcelPath      = "./excel"            # excel存放目录

